### ISSUE TITLE
Code autocompletion

### ISSUE THREAD

**Issue by Eragoneq** [katharostech/ldtk-rs#6]
Hi, I have a question about the code completion for the ldtk schema fields. I'm using Intelij and I wanted to be able to see the fields description of the different structs. Is there a proper way to enable this?

**Comment by zicklag** [comment]
I haven't used Intelij before, so I don't know. :thinking:

In VSCode I use rust-analyzer, and the latest few versions will automatically load the autocompletion for the crate. The issue is that the crate code is actually automatically generated at compile time, so the autocomplete engine needs to be configured to load the generated code.

You may want to see if there are settings for the Rust integration with Intelij. Look for something like "load out dir" or "cargo check before load" or "build.rs" or something similar.

**Comment by Eragoneq** [comment]
For anyone else interested that could be the solution: https://github.com/intellij-rust/intellij-rust/issues/1908 
I cannot really get this to work for now, so I'm just gonna manually use the documentation.
